// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dnubekktiyzmhznvrfcn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRudWJla2t0aXl6bWh6bnZyZmNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2MDU2MzIsImV4cCI6MjA2MTE4MTYzMn0.iQD93TUgwuyUcP_69wmc1OOkU_50VE6Pu8SRA9r5mLs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);